//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner.Log {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.Log.LogStrings", typeof(LogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 飞行日志正在下载，确定要中断？.
        /// </summary>
        public static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认？.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating KML for {0}.
        /// </summary>
        public static string CreatingKmlPrompt {
            get {
                return ResourceManager.GetString("CreatingKmlPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载飞行日志到: {0}.
        /// </summary>
        public static string DownloadStarting {
            get {
                return ResourceManager.GetString("DownloadStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!Allow 30-90 seconds for erase.
        /// </summary>
        public static string EraseComplete {
            get {
                return ResourceManager.GetString("EraseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing file. Make sure the file is not in use.
        /// </summary>
        public static string ErrorProcessingLogfile {
            get {
                return ResourceManager.GetString("ErrorProcessingLogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取飞行日志 {0} ....
        /// </summary>
        public static string FetchingLog {
            get {
                return ResourceManager.GetString("FetchingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取飞行日志列表中....
        /// </summary>
        public static string FetchingLogfileList {
            get {
                return ResourceManager.GetString("FetchingLogfileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法创建飞行日志目录: {0}.
        /// </summary>
        public static string LogDirectoryError {
            get {
                return ResourceManager.GetString("LogDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无飞行日志.
        /// </summary>
        public static string NoLogsFound {
            get {
                return ResourceManager.GetString("NoLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 飞行器未连接，请先连接飞行器.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请勾选要下载的飞行日志.
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0}.
        /// </summary>
        public static string ProcessingLog {
            get {
                return ResourceManager.GetString("ProcessingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在 {0} 个飞行日志.
        /// </summary>
        public static string SomeLogsFound {
            get {
                return ResourceManager.GetString("SomeLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误：.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
    }
}
